---
- include: do_reconfigure.yml
  serial: "30%"
  when: inventory_hostname in groups['trove-api'] or
        inventory_hostname in groups['trove-conductor'] or
        inventory_hostname in groups['trove-taskmanager']
